name: 'open_solar_dbt'
version: '1.0.0'
config-version: 2

profile: 'open_solar'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

models:
  open_solar_dbt:
    +materialized: table

seeds:
  open_solar_dbt:
    +schema: analytics
